routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\GoogleCalendar\Event;
use App\Http\Controllers\TripController;
use App\Http\Controllers\AdduserController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\PassengerController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\AdddriverController;
use App\Http\Controllers\AddvehicleController;
// use App\Http\Controllers\ViewvehicleController;
// use App\Http\Controllers\EditvehicleController;
// use App\Http\Controllers\AddfareController;
use App\Http\Controllers\FareController;
// use App\Http\Controllers\EditdriverController;
use App\Http\Controllers\PaymenteditController;
// use App\Http\Controllers\EditpassengerController;
// use App\Http\Controllers\EditfareController;
use App\Http\Controllers\BookedtripController;
use App\Http\Controllers\RevenueController;
use App\Http\Controllers\AccountController;
// use App\Http\Controllers\ViewaccountController;
use App\Http\Controllers\PaypalController;










/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Artisan commands
Route::get('clear-cache', function () {

    \Artisan::call('cache:clear');

    dd("Cache is cleared");

});

Route::get('view-clear', function () {

    \Artisan::call('view:clear');

    dd("View is cleared");

});

Route::get('config-clear', function () {

    \Artisan::call('config:clear');

    dd("Config is cleared");

});

Route::get('config-cache', function () {

    \Artisan::call('config:cache');

    dd("Config cache is cleared");

});

Route::get('route-clear', function () {

    \Artisan::call('route:clear');

    dd("Route is cleared");

});

Route::get('route-cache', function () {

    \Artisan::call('route:cache');

    dd("Route is cached");

});

Route::get('optimize', function () {

    \Artisan::call('optimize');

    dd("Cache optimized");

});

Route::get('migrate', function () {

    \Artisan::call('migrate');

    dd("Database migrated");

});

Route::get('db-seed', function () {

    \Artisan::call('db:seed');

    dd("Database seeded");

});

Route::get('/test', function () {
    $event = new Event;
    $event->name = 'Todays Meeting for Example';
    $event->startDateTime = Carbon\Carbon::now();
    $event->endDateTime = Carbon\Carbon::now()->addHour();
    $event->save();
    $e = Event::get();

    dd($e);
});
Route::get('/', function () {
    return view('welcome');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/contact', function () {
    return view('contact');
});



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
Route::get('/addmeeting', [App\Http\Controllers\AddmeetingController::class, 'index'])->name('addmeeting');
Route::get('/allmeeting/{category?}/{startingdate?}/{endingdate?}/{user_id?}', [App\Http\Controllers\AllMeetingController::class, 'index'])->name('allmeeting');
Route::get('/editmeeting/{id}', [App\Http\Controllers\AllMeetingController::class, 'show'])->name('editmeeting/{id}');
Route::get('/meetingNotification', [App\Http\Controllers\MeetingNotificationController::class, 'index'])->name('meetingNotification');
Route::post('/add', [App\Http\Controllers\AdduserController::class, 'create'])->name('add');
Route::post('/', [App\Http\Controllers\AddmeetingController::class, 'create'])->name('/');
Route::post('/update', [App\Http\Controllers\AllMeetingController::class, 'edit'])->name('update');
Route::delete('/delmeeting/{id}', [App\Http\Controllers\AllMeetingController::class, 'destroy'])->name('Meeting.destroy');
Route::post('/submit', [App\Http\Controllers\ContactController::class, 'create'])->name('submit');
Route::get('/event', [App\Http\Controllers\AddEventController::class, 'index'])->name('event');
Route::get('/calendar', [App\Http\Controllers\CalendarController::class, 'index'])->name('calendar');
Route::get('/contacts', [App\Http\Controllers\ContactController::class, 'index'])->name('contacts');
//ALL PASSENGER ROUTE
Route::get('/passenger', [App\Http\Controllers\PassengerController::class, 'index'])->name('passenger');
// Route::get('/analyze', [App\Http\Controllers\AnalyzeController::class, 'index'])->name('analyze');
// PAYMENT ROUTE
Route::get('/payment', [App\Http\Controllers\PaymentController::class, 'index'])->name('payment');
//ADD DRIVER ROUTE
Route::group(['prefix' => 'adddriver', 'as' => 'adddriver.'], function () {
      Route::get('/create', [AdddriverController::class, 'index'])->name('create');
      Route::get('/alldriver', [AdddriverController::class, 'view'])->name('alldriver');
      Route::post('/store', [AdddriverController::class, 'store'])->name('store');
      //EDIT DRIVER ROUTE
      Route::get('/editdriver/{id}', [AdddriverController::class, 'edit'])->name('editdriver');
      Route::post('update-data', [AdddriverController::class, 'update'])->name('update-data');
      Route::get('delete-data/{id}', [AdddriverController::class, 'delete'])->name('delete-data');
});
//ADD VEHICLE ROUTE
Route::group(['prefix' => 'addvehicle', 'as' => 'addvehicle.'], function () {
      Route::get('/create', [AddvehicleController::class, 'index'])->name('create');
      Route::get('/viewvehicle', [AddvehicleController::class, 'view'])->name('viewvehicle');
      Route::post('/store', [AddvehicleController::class, 'store'])->name('store');
      Route::get('/editvehicle/{id}', [AddvehicleController::class, 'edit'])->name('editvehicle');
      Route::post('update-data', [AddvehicleController::class, 'update'])->name('update-data');
      Route::get('delete-data/{id}', [AddvehicleController::class, 'delete'])->name('delete-data');



});
// VIEW VEHICLE ROUTE




//ADD FARE ROUTE
Route::group(['prefix' => 'fare', 'as' => 'fare.'], function () {
    Route::get('/create', [FareController::class, 'index'])->name('create');
    Route::get('/all', [FareController::class, 'view'])->name('all');
    Route::post('/store', [FareController::class, 'store'])->name('store');
    Route::get('edit/{id}', [FareController::class, 'edit'])->name('edit');
    Route::post('update-data', [FareController::class, 'update'])->name('update-data');
    Route::get('delete-data/{id}', [FareController::class, 'delete'])->name('delete-data');

});



//PAYMENT EDIT ROUTE
Route::get('/paymentedit', [App\Http\Controllers\PaymenteditController::class, 'index'])->name('paymentedit');
// EDIT PASSENGER ROUTE
Route::group(['prefix' => 'passenger', 'as' => 'passenger.'], function () {
    Route::get('/passenger', [PassengerController::class, 'index'])->name('passenger');
    Route::get('delete-data/{id}', [PassengerController::class, 'delete'])->name('delete-data');

    // Route::get('/editpassenger', [PassengerController::class, 'edit'])->name('editpassenger');
    // Route::post('update-data', [PassengerController::class, 'update'])->name('update-data');
});

// BOOKED TRIPS
Route::get('/bookedtrip', [App\Http\Controllers\BookedtripController::class, 'index'])->name('bookedtrip');
//REVENUE
Route::get('/revenue', [App\Http\Controllers\RevenueController::class, 'index'])->name('revenue');
// ADD DRIVER ACCOUNT DETAILS
Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
    Route::get('/create', [AccountController::class, 'index'])->name('create');
    Route::get('/viewaccount', [AccountController::class, 'view'])->name('viewaccount');
    Route::post('/store', [AccountController::class, 'store'])->name('store');
    Route::get('accountedit/{id}', [AccountController::class, 'edit'])->name('accountedit');
    Route::post('update-data', [AccountController::class, 'update'])->name('update-data');
    Route::get('delete-data/{id}', [AccountController::class, 'delete'])->name('delete-data');
    });
//VIEW DRIVERS ACCOUNT
// Route::get('/viewaccount', [App\Http\Controllers\ViewaccountController::class, 'index'])->name('viewaccount');
Route::get('/paypal', [App\Http\Controllers\PaypalController::class, 'index'])->name('paypal');



Route::get('/report/{category?}/{startingdate?}/{endingdate?}/{user_id?}', [App\Http\Controllers\ReportController::class, 'index'])->name('report');
Route::get('/report-status/{meeting_id}/{meeting_status}', [App\Http\Controllers\ReportController::class, 'meetingStatus']);

//Role
Route::group(['prefix' => 'trip', 'as' => 'role.'], function () {
    Route::get('/create', [TripController::class, 'create'])->name('create');
    Route::post('/store', [TripController::class, 'store'])->name('store');
    Route::get('/all', [TripController::class, 'all'])->name('all');
    Route::post('/update', [TripController::class, 'update'])->name('update');
});
//User
Route::group(['prefix' => 'driver', 'as' => 'user.'], function () {
    Route::get('/addUser', [DriverController::class, 'index'])->name('addUser');
    Route::get('/alluser/{startingdate?}/{endingdate?}/{user_id?}', [DriverController::class, 'index'])->name('alluser');
    Route::get('/edit-user/{id}', [DriverController::class, 'editUser'])->name('edit-user');
    Route::post('/update-user', [DriverController::class, 'updateUser'])->name('update-user');
    Route::delete('/del/{id}', [DriverController::class, 'destroy'])->name('users.destroy');
});
//End User
//Meeting
Route::group(['prefix' => 'meeting', 'as' => 'meeting.'], function () {
});
//End Meeting
//Meeting Reporting
Route::group(['prefix' => 'meeting-report', 'as' => 'meeting-report.'], function () {
});






//ADD FARE ROUTE
Route::group(['prefix' => 'fare', 'as' => 'fare.'], function () {

resources/views/AfterLogin/accontedit.blade.php
@extends('layouts.section.dashboards')
@section('content')

<div class="content-wrapper mt-5 py-4">

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-success card-outline">
                <div class="card-header">
                    <h1 class="card-title">Driver Account Details</h1>
                </div>
<form action= "{!! url('account/update-data') !!}" method="POST">
@csrf
<input type="hidden" value="{{$driver_accounts->id}}" name="edit"/>
                <div class="row px-3 my-4">
                               
                               <div class="col-sm-6 mb-2 my-4">
                                   <p class="mb-2 f-w-600">Bank's Name</p>
                                   <!-- <label for="cars">Choose Vehicle Type</label> -->
                                   <!-- <select id="bank_name" class="form-control in1" name="bank_name">
                                    <option value="Vehicle">Select Bank's</option>
                                    <option value="suv">JPMorgan Chase</option>
                                    <option value="Sedan">Bank of America</option>
                                    <option value="van">Citigroup</option>
                                    <option value="wagon">U.S. Bancorp </option>
                                   </select> -->
                                   <input type="text" class="form-control in1" value="{{$driver_accounts->bank_name}}" name="bank_name">
                           
                               </div>
                              
                               <!-- <div class="col-sm-6 mb-2 my-4">
                                  <p class="mb-2 f-w-600">Name Of The Account Holder</p>
                                  <input class="form-control in1" type="text" name="driver_id" id="driver_id">
                               </div>                               -->
                              
                               <div class="col-sm-6 mb-2  my-4">
                                   <p class="mb-2 f-w-600">Account Number</p>
                                   <input class="form-control in1" type="text" value="{{$driver_accounts->account_number}}" name="account_number" id="account_number" >
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->number }}</h6> -->
                               </div>
                               <div class="col-sm-6 mb-2 my-4 ">
                                   <p class="mb-2 f-w-600">Routing Code</p>
                                   <input class="form-control in1" type="text" value="{{$driver_accounts->routing_number}}" name="routing_number" id="routing_number">
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->employee_id }}</h6> -->
                               </div>

                              
                              
                             </div>
                           <br>
                        <div class="col-lg-12 p-t-20 text-center">
                        <input type="submit" value="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 my-3 btn btn-info" data-upgraded=",MaterialButton,MaterialRipple">

										<!-- <button type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 my-3 btn btn-info" data-upgraded=",MaterialButton,MaterialRipple">Submit<span class="mdl-button__ripple-container"><span class="mdl-ripple is-animating"></span></span></button> -->
									
									</div>                         
                   </form>
            </div>
        </div>
    </div>
</section>
</div>







<!-- css add  -->




  <style>
.name h3 {
  font-family: "Trirong", serif;
}

.name2 p {
  font-family: "Trirong", serif;
}
.in1 {
  border: none;
  border-bottom: 1px solid green;
 

}

/* .container{
  margin-left: 20%;

} */
.row>* {
    flex-shrink: 0;
    width: 100%;
    max-width: 100%;
    padding-right: calc(var(--bs-gutter-x)/ 2);
    padding-left: calc(var(--bs-gutter-x)/ 2);
    margin-top: var(--bs-gutter-y);
}


</style>
@endsection

resources/views/AfterLogin/addfare.blade.php
@extends('layouts.section.dashboards')
@section('content')

<div class="content-wrapper mt-5 py-4">

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-success card-outline">
                <div class="card-header">
                    <h1 class="card-title">Add Fare</h1>
                </div>
<form action="{!! route('fare.store') !!}" method="POST">
  @csrf
                <div class="row px-3 my-4">
                               
                               <div class="col-sm-6 mb-2 my-4">
                                   <p class="mb-2 f-w-600">Vehicle Types</p>
                                   <!-- <label for="cars">Choose Vehicle Type</label> -->
                                   <select id="cars" class="form-control in1" name="vehicle_type">
                                   <option value="Vehicle">Select Vehicle Type</option>
                                    <option value="suv">Large SUV</option>
                                    <option value="Sedan">Sedan</option>
                                    <option value="van">Mid Size SUV</option>
                                    <option value="wagon">Mini SUV</option>
                                    <option value="wagon">Hatchback</option>
                                    <option value="wagon">Convertible</option>
                                    <option value="wagon">Coupe</option>
                                    <option value="wagon">Sports Car</option>
                                    <option value="wagon">Mini Van</option>
                                    <option value="wagon">Hatchback</option>
                                   </select>
                           
                               </div>
                              
                               <div class="col-sm-6 mb-2 my-4">
                                  <p class="mb-2 f-w-600">Fare Per KM (in $)</p>
                                  <input class="form-control in1" type="text" name="fare_per_km" id="fare_per_km">
                               </div>      
                               <div class="col-sm-6 mb-2  my-4">
                                   <p class="mb-2 f-w-600"> Fare per minute (in $)</p>
                                   <input class="form-control in1" type="text" name="fare_per_minute" id="fare_per_minute" >
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->number }}</h6> -->
                               </div>                        
                              
                               <div class="col-sm-6 mb-2  my-4">
                                   <p class="mb-2 f-w-600">Minimun Fare (in $)</p>
                                   <input class="form-control in1" type="text" name="minimun_fare" id="minimun_fare" >
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->number }}</h6> -->
                               </div>
                               <div class="col-sm-6 mb-2 my-4 ">
                                   <p class="mb-2 f-w-600">Minimun Distance (in KM)</p>
                                   <input class="form-control in1" type="text" name="minimun_distance" id="minimun_distance">
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->employee_id }}</h6> -->
                               </div>

                               <div class="col-sm-6 mb-2 my-4">
                                   <p class="mb-2 f-w-600">Waiting Fare (in $)</p>
                                   <input class="form-control in1" type="text" name="waiting_fare" id="waiting_fare" >
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->employee_id }}</h6> -->
                               </div>
                              
                             </div>
                           <br>
                        <div class="col-lg-12 p-t-20 text-center">
                          <input type="submit" value="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 my-3 btn btn-info" data-upgraded=",MaterialButton,MaterialRipple">
									
									
									</div>                         
                   </form>
            </div>
        </div>
    </div>
</section>
</div>







<!-- css add  -->




  <style>
.name h3 {
  font-family: "Trirong", serif;
}

.name2 p {
  font-family: "Trirong", serif;
}
.in1 {
  border: none;
  border-bottom: 1px solid green;
 

}

/* .container{
  margin-left: 20%;

} */
.row>* {
    flex-shrink: 0;
    width: 100%;
    max-width: 100%;
    padding-right: calc(var(--bs-gutter-x)/ 2);
    padding-left: calc(var(--bs-gutter-x)/ 2);
    margin-top: var(--bs-gutter-y);
}


</style>
@endsection

resources/views/AfterLogin/analyze.blade.php
@extends('layouts.section.dashboards')
@section('content')

<div class="content-wrapper mt-5 py-3">
    <!-- Content Header (Page header) -->
      <!-- /.container-fluid -->
    <!-- /.content-header -->
    <!-- /.row (main row) -->
    <!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
             <div class="mb-3 row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Meeting Id</label>
                <div class="col-sm-10">
                  <h6 id="id_meeting"></h6>
                </div>
                <label for="staticEmail" class="col-sm-2 col-form-label">Meeting-Caegory</label>
                <div class="col-sm-10">
                    <h6 id="category"></h6>
                  </div>
            </div>                         
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
    <section class="content">
      <div class="container-fluid mb-5">
          <div class="row">
              <div class="col-md-12">
                  <div class="card text-center">
                    <div class="row px-3 py-2">
                        <div class="col-6 mt-4 d-flex">
                            <input class="form-control" type="search" placeholder="Search with meeting name" id="search" aria-label="Search">
                          
                        </div>
                        <div class="col-3 mt-4 d-flex">
                            
                            <select class="form-select" aria-label="Default select example">
                                <option selected>Select Filter</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                              </select>
                        </div>
                        <div class="col-3 mt-4">
                        
                            <select class="form-select" aria-label="Default select example">
                                
                            </select>
                        </div>
                    </div>
                      <div class="card-body ">
                          <div class="table-responsive pb-3">
                              <table id="user-table" class="table table-bordered table-hover">
                                  <thead>
                                    <tr>
                                      <th>Sr</th>
                                      <th>Meeting Name</th>
                                      <th>Meeting Id</th>
                                      <th>Date</th>
                                      <th>Host Name</th>
                                      <th>Meeting Catogary</th>
                                      <th>Download Report</th>
                                    </tr>
                                  </thead>
                                  <tbody class="article-table">
                                      @foreach($addmeeting as $key=>$meeting)
                                      <tr data-widget="expandable-table" aria-expanded="false">
                                        <td>{{intval($key)+1}}</td>
                                        <td>{{$meeting->meeting_name}}</td>
                                        <td>{{$meeting->meeting_id}}</td>
                                        <td>{{$meeting->meeting_date}}</td>
                                        <td>{{$meeting->host_name}}</td>
                                        <td>{{$meeting->category}}</td>
                                        <td><a data-target-id="{{ $meeting->id }}" data-target-name="{{$meeting->meeting_name}}" data-target-category="{{$meeting->category}}" type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                            Download
                                        </a>
                                      </tr>
                                      @endforeach
                                  </tbody>    
                              </table>
                              {{ $addmeeting->links() }}
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
</div>
  <script>
    $("#search").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $(".article-table tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
    });   

            $(document).ready(function () {
                $("#exampleModal").on("show.bs.modal", function (e) {
                    var id = $(e.relatedTarget).data('target-id');
                    var name = $(e.relatedTarget).data('target-name');
                    var category = $(e.relatedTarget).data('target-category');
                    $('#id_meeting').text(id);
                    $('#exampleModalLabel').text(name);
                    $('#category').text(category);
                });
            });


</script>
@endsection

resources/views/AfterLogin/create.blade.php
@extends('layouts.section.dashboards')
@section('content')

<div class="content-wrapper mt-5 py-4">

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-success card-outline">
                <div class="card-header">
                    <h1 class="card-title">Driver Account Details</h1>
                </div>
<form action= "{!! route('account.store') !!}" method="POST">
@csrf
                <div class="row px-3 my-4">
                               
                               <div class="col-sm-6 mb-2 my-4">
                                   <p class="mb-2 f-w-600">Bank's Name</p>
                                   <!-- <label for="cars">Choose Vehicle Type</label> -->
                                   <!-- <select id="bank_name" class="form-control in1" name="bank_name">
                                    <option value="Vehicle">Select Bank's</option>
                                    <option value="suv">JPMorgan Chase</option>
                                    <option value="Sedan">Bank of America</option>
                                    <option value="van">Citigroup</option>
                                    <option value="wagon">U.S. Bancorp </option>
                                   </select> -->
                                   <input type="text" class="form-control in1" name="bank_name">
                           
                               </div>
                              
                               <!-- <div class="col-sm-6 mb-2 my-4">
                                  <p class="mb-2 f-w-600">Name Of The Account Holder</p>
                                  <input class="form-control in1" type="text" name="driver_id" id="driver_id">
                               </div>                               -->
                              
                               <div class="col-sm-6 mb-2  my-4">
                                   <p class="mb-2 f-w-600">Account Number</p>
                                   <input class="form-control in1" type="text" name="account_number" id="account_number" >
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->number }}</h6> -->
                               </div>
                               <div class="col-sm-6 mb-2 my-4 ">
                                   <p class="mb-2 f-w-600">Routing Code</p>
                                   <input class="form-control in1" type="text" name="routing_number" id="routing_number">
                                   <!-- <h6 class="text-muted f-w-400">{{ Auth::user()->employee_id }}</h6> -->
                               </div>

                              
                              
                             </div>
                           <br>
                        <div class="col-lg-12 p-t-20 text-center">
                        <input type="submit" value="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 my-3 btn btn-info" data-upgraded=",MaterialButton,MaterialRipple">

										<!-- <button type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 my-3 btn btn-info" data-upgraded=",MaterialButton,MaterialRipple">Submit<span class="mdl-button__ripple-container"><span class="mdl-ripple is-animating"></span></span></button> -->
									
									</div>                         
                   </form>
            </div>
        </div>
    </div>
</section>
</div>







<!-- css add  -->




  <style>
.name h3 {
  font-family: "Trirong", serif;
}

.name2 p {
  font-family: "Trirong", serif;
}
.in1 {
  border: none;
  border-bottom: 1px solid green;
 

}

/* .container{
  margin-left: 20%;

} */
.row>* {
    flex-shrink: 0;
    width: 100%;
    max-width: 100%;
    padding-right: calc(var(--bs-gutter-x)/ 2);
    padding-left: calc(var(--bs-gutter-x)/ 2);
    margin-top: var(--bs-gutter-y);
}


</style>
@endsection